// Warehouse v2: multi-agent 2.5D warehouse with rack levels 1..6.
class RNG{constructor(seed=71){this.s=seed>>>0}next(){this.s=(1664525*this.s+1013904223)>>>0;return this.s/4294967296}int(a,b){return a+Math.floor(this.next()*(b-a+1))}}
export class WarehouseV2{
 constructor(seed=2026,flyCount=4){this.seed=seed;this.flyCount=flyCount;this.reset()}
 event(type,message,fly=null){this.events.unshift({t:this.t,type,message,fly});this.events=this.events.slice(0,120)}
 reset(){const r=new RNG(this.seed);this.t=0;this.score=0;this.collisions=0;this.completed=0;this.finished=false;this.events=[];this.racks=[];this.inventory=[];this.docks=[{x:2,y:23},{x:6,y:23},{x:10,y:23},{x:14,y:23}];
  for(let aisle=0;aisle<8;aisle++)for(let bay=0;bay<12;bay++){const levels=r.int(1,6),x=2+aisle*2,y=2+bay*1.6;this.racks.push({aisle,bay,x,y,levels});for(let level=1;level<=levels;level++)if(r.next()<.72)this.inventory.push({id:`P-${aisle}-${bay}-${level}`,sku:`SKU-${String(r.int(1,1000)).padStart(4,'0')}`,lot:r.int(1,20),weight:r.int(300,1050),aisle,bay,level})}
  this.flies=Array.from({length:this.flyCount},(_,i)=>({id:i+1,x:1+(i%4)*3.5,y:21.5-Math.floor(i/4)*.65,z:0,load:null,target:null,distance:0,status:'idle',blocked:false,lastStatus:'idle'}));const picks=[];for(let i=0;i<6;i++){const p=this.inventory[i*5];if(p)picks.push(p)}this.orders=picks.map((p,i)=>({id:`ORD-${i+1}`,sku:p.sku,qty:1,done:0,rule:'FIFO',dock:i%4}));this.event('system',`Shift started · ${this.flyCount} flies · ${this.inventory.length} pallets · ${this.orders.length} orders`);this.assign()}
 setFlyCount(n){this.flyCount=n;this.reset()}
 rackFor(p){return this.racks.find(q=>q.aisle===p.aisle&&q.bay===p.bay)}
 assign(){for(const f of this.flies){if(f.load||f.target)continue;const o=this.orders.find(o=>o.done<o.qty&&!this.flies.some(x=>x.target?.order===o.id));if(!o)continue;const p=this.inventory.filter(p=>p.sku===o.sku).sort((a,b)=>a.lot-b.lot)[0];if(p){f.target={order:o.id,pallet:p.id,phase:'pickup'};f.status='to rack';this.event('assign',`FLY ${f.id} assigned ${o.id} → A${p.aisle+1}/B${p.bay+1}/L${p.level} · ${p.sku}`,f.id)}}}
 moveToward(f,tx,ty){const dx=tx-f.x,dy=ty-f.y;const nx=f.x+(Math.abs(dx)>.08?Math.sign(dx)*.12:0),ny=f.y+(Math.abs(dx)<=.08&&Math.abs(dy)>.08?Math.sign(dy)*.12:0);const blocker=this.flies.find(o=>o!==f&&Math.hypot(o.x-nx,o.y-ny)<.18);if(blocker){if(!f.blocked)this.event('wait',`FLY ${f.id} blocked by FLY ${blocker.id}`,f.id);f.blocked=true;f.status='waiting';return}if(f.blocked)this.event('move',`FLY ${f.id} path clear · moving`,f.id);f.blocked=false;f.x=nx;f.y=ny;f.distance+=.12}
 step(){if(this.finished)return this.state();this.t++;for(const f of this.flies){if(!f.target)continue;const o=this.orders.find(o=>o.id===f.target.order);if(!o){f.target=null;continue}if(f.target.phase==='pickup'){const p=this.inventory.find(p=>p.id===f.target.pallet);if(!p){f.target=null;continue}const rack=this.rackFor(p);this.moveToward(f,rack.x,rack.y);if(Math.abs(f.x-rack.x)<.15&&Math.abs(f.y-rack.y)<.15){if(f.status!=='lifting')this.event('arrive',`FLY ${f.id} arrived A${p.aisle+1}/B${p.bay+1} · lifting to L${p.level}`,f.id);f.z+=(p.level-f.z)*.3;f.status='lifting';if(Math.abs(f.z-p.level)<.12){f.load=p;this.inventory=this.inventory.filter(x=>x.id!==p.id);f.target.phase='dock';f.status='loaded';this.event('pick',`FLY ${f.id} picked ${p.id} · ${p.sku} · ${p.weight} kg`,f.id)}}}else{const d=this.docks[o.dock];f.z+=(0-f.z)*.4;this.moveToward(f,d.x,d.y);if(Math.abs(f.x-d.x)<.15&&Math.abs(f.y-d.y)<.15&&f.z<.15){o.done++;this.completed++;this.score+=10;this.event('complete',`FLY ${f.id} unloaded at DOCK ${o.dock+1} · ${o.id} completed`,f.id);f.load=null;f.target=null;f.status='idle'}}}
  for(let i=0;i<this.flies.length;i++)for(let j=i+1;j<this.flies.length;j++){const a=this.flies[i],b=this.flies[j];if(Math.hypot(a.x-b.x,a.y-b.y)<.12&&!a.blocked&&!b.blocked){this.collisions++;this.score-=1;this.event('collision',`Collision FLY ${a.id} ↔ FLY ${b.id}`) }}
  this.assign();this.finished=this.orders.length>0&&this.orders.every(o=>o.done>=o.qty);if(this.finished)this.event('finish',`SHIFT COMPLETE · ${this.completed} orders · score ${this.score.toFixed(1)} · collisions ${this.collisions}`);return this.state()}
 state(){return{t:this.t,score:this.score,collisions:this.collisions,completed:this.completed,finished:this.finished,flyCount:this.flyCount,racks:this.racks,inventory:this.inventory,flies:this.flies.map(f=>({...f})),orders:this.orders.map(o=>({...o})),docks:this.docks,events:[...this.events]}}
}