// Deterministic warehouse generator: 1000-SKU catalogue, mixed inbound/outbound,
// packaging geometry and physical trailer constraints. Values are simulation defaults
// and intentionally editable rather than claims about a specific supplier.
class RNG{constructor(seed=71){this.s=seed>>>0}next(){this.s=(1664525*this.s+1013904223)>>>0;return this.s/4294967296}int(a,b){return a+Math.floor(this.next()*(b-a+1))}pick(a){return a[this.int(0,a.length-1)]}}
const TYPES=[
 {product:'preform',package:'octabin',dims:[1200,1000,1150],gross:[450,850],stackable:true,maxStack:2},
 {product:'cap',package:'pallet',dims:[1200,1000,1600],gross:[250,650],stackable:false,maxStack:1},
 {product:'resin',package:'bigbag',dims:[1200,1000,1250],gross:[1000,1100],stackable:false,maxStack:1},
 {product:'film',package:'pallet',dims:[1200,1000,1500],gross:[400,900],stackable:false,maxStack:1}
];
export function makeCatalogue(seed=71,count=1000){const r=new RNG(seed);return Array.from({length:count},(_,i)=>{const t=r.pick(TYPES);return{id:`SKU-${String(i+1).padStart(4,'0')}`,product:t.product,package:t.package,length:t.dims[0],width:t.dims[1],height:t.dims[2],grossWeight:r.int(t.gross[0],t.gross[1]),stackable:t.stackable,maxStack:t.maxStack,rotation:true,rule:r.next()<.82?'FIFO':r.next()<.7?'FEFO':'LIFO'}})}
export function trailerPreset(kind='standard'){return kind==='mega'?{id:'MEGA',length:13620,width:2480,height:2845,maxPayload:33000}:{id:'STANDARD',length:13620,width:2480,height:2700,maxPayload:33000}}
export function floorPositions(trailer,l=1200,w=1000){const layouts=[[l,w],[w,l]].map(([a,b])=>({cols:Math.floor(trailer.length/a),rows:Math.floor(trailer.width/b),count:Math.floor(trailer.length/a)*Math.floor(trailer.width/b),a,b}));return layouts.sort((a,b)=>b.count-a.count)[0]}
export class WarehouseRoom{
 constructor(seed=71){this.seed=seed;this.reset()}
 reset(){const r=new RNG(this.seed);this.rng=r;this.catalogue=makeCatalogue(this.seed,1000);this.t=0;this.score=0;this.violations=0;this.distance=0;this.truckWait=0;this.fork={x:1,y:7,load:null};this.slots=[];this.inbound=[];let n=0;
  // Visible operational sample drawn from the 1000-SKU master catalogue.
  for(let y=0;y<6;y++)for(let x=0;x<7;x++){const sku=this.catalogue[r.int(0,79)];this.slots.push({x:x+1,y:y+1,sku:sku.id,product:sku.product,package:sku.package,lot:260800+r.int(1,12),productionDay:r.int(1,240),expiryDay:r.int(250,700),weight:sku.grossWeight,dims:[sku.length,sku.width,sku.height],id:`P${String(++n).padStart(3,'0')}`})}
  // Mixed inbound staging: new pallets/octabins waiting for put-away.
  for(let i=0;i<10;i++){const sku=this.catalogue[r.int(0,99)];this.inbound.push({id:`IN-${i+1}`,sku:sku.id,product:sku.product,package:sku.package,weight:sku.grossWeight,lot:260900+r.int(1,6)})}
  const available=[...new Set(this.slots.map(p=>p.sku))];this.orders=Array.from({length:4},(_,i)=>{const sku=available[(i*7)%available.length];const meta=this.catalogue.find(s=>s.id===sku);const trailer=trailerPreset(i===3?'mega':'standard');const fp=floorPositions(trailer,meta.length,meta.width);const physical=Math.min(fp.count*(meta.stackable?Math.min(meta.maxStack,Math.floor(trailer.height/meta.height)):1),Math.floor(trailer.maxPayload/meta.grossWeight));return{id:`TRUCK-${i+1}`,sku,product:meta.product,package:meta.package,qty:Math.min(r.int(3,8),this.slots.filter(p=>p.sku===sku).length),rule:meta.rule,loaded:0,loadedWeight:0,trailer,physicalCapacity:physical}});this.events=[]}
 activeOrder(){return this.orders.find(o=>o.loaded<o.qty)}
 targetFor(o){if(!o)return null;const c=this.slots.filter(p=>p.sku===o.sku);if(!c.length)return null;if(o.rule==='LIFO')return c.sort((a,b)=>b.productionDay-a.productionDay)[0];if(o.rule==='FEFO')return c.sort((a,b)=>a.expiryDay-b.expiryDay)[0];return c.sort((a,b)=>a.productionDay-b.productionDay)[0]}
 sensors(){const o=this.activeOrder(),target=this.targetFor(o);return{targetDx:target?Math.sign(target.x-this.fork.x):0,targetDy:target?Math.sign(target.y-this.fork.y):0,atTarget:!!target&&target.x===this.fork.x&&target.y===this.fork.y,carrying:!!this.fork.load,atDock:this.fork.x===9&&this.fork.y===7,reward:Math.max(0,this.score/30),heat:0,energyLow:0,waterLow:0,danger:0}}
 step(action){this.t++;const pre=this.sensors();if(action==='left'){this.fork.x=Math.max(0,this.fork.x-1);this.distance++}if(action==='right'){this.fork.x=Math.min(9,this.fork.x+1);this.distance++}if(action==='up'){this.fork.y=Math.max(0,this.fork.y-1);this.distance++}if(action==='down'){this.fork.y=Math.min(7,this.fork.y+1);this.distance++}
  if(action==='pick'&&!this.fork.load){const i=this.slots.findIndex(p=>p.x===this.fork.x&&p.y===this.fork.y);if(i>=0){this.fork.load=this.slots.splice(i,1)[0];this.events.push(`Picked ${this.fork.load.id} ${this.fork.load.sku}`)}}
  if(action==='drop'&&this.fork.load&&pre.atDock){const o=this.activeOrder(),p=this.fork.load;if(o&&p.sku===o.sku){const expected=this.targetFor(o);if(expected&&((o.rule==='FIFO'&&expected.productionDay<p.productionDay)||(o.rule==='LIFO'&&expected.productionDay>p.productionDay)||(o.rule==='FEFO'&&expected.expiryDay<p.expiryDay))){this.violations++;this.score-=3;this.events.push(`${o.rule} VIOLATION`)}else if(o.loadedWeight+p.weight>o.trailer.maxPayload||o.loaded>=o.physicalCapacity){this.violations++;this.score-=5;this.events.push('TRAILER CAPACITY VIOLATION')}else{this.score+=5;o.loaded++;o.loadedWeight+=p.weight;this.events.push(`Loaded ${p.id} → ${o.id}`)}}else{this.score-=3;this.violations++}this.fork.load=null}
  this.truckWait+=this.orders.filter(o=>o.loaded<o.qty).length;return this.state()}
 state(){return{t:this.t,score:this.score,violations:this.violations,distance:this.distance,truckWait:this.truckWait,catalogueSize:this.catalogue.length,inboundCount:this.inbound.length,fork:{...this.fork},slots:this.slots.map(x=>({...x})),orders:this.orders.map(x=>({...x})),events:[...this.events]}}
}