import express from 'express';import cors from 'cors';import pg from 'pg';
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS experiment_runs(id BIGSERIAL PRIMARY KEY,run_id TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),seed INT,brain TEXT,flies INT,ticks INT,completed INT,total INT,score DOUBLE PRECISION,collisions INT,reason TEXT,events JSONB DEFAULT '[]'::jsonb,config JSONB DEFAULT '{}'::jsonb)`)}
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/runs',async(req,res)=>{try{const r=req.body,runId=r.runId||`RUN-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const q=`INSERT INTO experiment_runs(run_id,seed,brain,flies,ticks,completed,total,score,collisions,reason,events,config) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(run_id) DO UPDATE SET ticks=EXCLUDED.ticks,completed=EXCLUDED.completed,total=EXCLUDED.total,score=EXCLUDED.score,collisions=EXCLUDED.collisions,reason=EXCLUDED.reason,events=EXCLUDED.events,config=EXCLUDED.config RETURNING *`;const v=[runId,r.seed,r.brain,r.flies,r.ticks,r.completed,r.total,r.score,r.collisions,r.reason,JSON.stringify(r.events||[]),JSON.stringify(r.config||{})];res.json((await pool.query(q,v)).rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/runs/batch',async(req,res)=>{const runs=Array.isArray(req.body)?req.body:[];const saved=[];for(const r of runs){try{const runId=r.runId||`RUN-${Date.now()}-${saved.length}-${Math.random().toString(36).slice(2,6)}`;const q=`INSERT INTO experiment_runs(run_id,seed,brain,flies,ticks,completed,total,score,collisions,reason,events,config) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING run_id`;const v=[runId,r.seed,r.brain,r.flies,r.ticks,r.completed,r.total,r.score,r.collisions,r.reason,JSON.stringify(r.events||[]),JSON.stringify(r.config||{})];saved.push((await pool.query(q,v)).rows[0])}catch(e){saved.push({error:e.message})}}res.json({saved:saved.length,items:saved})});
app.get('/api/runs',async(req,res)=>{const limit=Math.min(500,Math.max(1,+req.query.limit||100));const rows=(await pool.query('SELECT * FROM experiment_runs ORDER BY created_at DESC LIMIT $1',[limit])).rows;res.json(rows)});
app.get('/api/summary',async(req,res)=>{const q=`SELECT COUNT(*)::int runs,COUNT(*) FILTER(WHERE reason='complete')::int complete,COUNT(*) FILTER(WHERE reason='deadlock')::int deadlocks,ROUND(AVG(ticks))::int avg_ticks,ROUND(AVG(score)::numeric,2) avg_score FROM experiment_runs`;res.json((await pool.query(q)).rows[0])});
init().then(()=>app.listen(process.env.PORT||10000,()=>console.log('Fly Brain Lab API ready'))).catch(e=>{console.error(e);process.exit(1)});
