import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SyntheticBrain} from './brain/SyntheticBrain';
import {ControlRoom} from './rooms/ControlRoom';
import {WarehouseRoom} from './rooms/WarehouseRoom';
import {WarehouseBrain} from './brain/WarehouseBrain';
import './style.css';
function App(){
 const [mode,setMode]=useState('station'),[running,setRunning]=useState(false),[speed,setSpeed]=useState(100),[neural,setNeural]=useState({spikes:[],action:'wait'}),[events,setEvents]=useState([]);const brain=useRef(),room=useRef();const [state,setState]=useState({});
 const init=(m=mode)=>{setRunning(false);if(m==='warehouse'){room.current=new WarehouseRoom(71);brain.current=new WarehouseBrain(71)}else{room.current=new ControlRoom(42);brain.current=new SyntheticBrain(42)}setState(room.current.step('wait'));setNeural({spikes:[],action:'wait'});setEvents([])};
 useEffect(()=>init(mode),[mode]);
 const step=()=>{const b=brain.current.step(room.current.sensors());const s=room.current.step(b.action);setNeural(b);setState(s);setEvents(e=>[`#${s.t} ${b.action.toUpperCase()} ${mode==='warehouse'?`score ${s.score} / FIFO ${s.violations}`:`T ${s.temp.toFixed(1)}° / integrity ${s.integrity.toFixed(1)}%`}`,...e].slice(0,14));if((s.integrity!==undefined&&s.integrity<=0)||(mode==='warehouse'&&s.orders.every(o=>o.loaded>=o.qty)))setRunning(false)};
 useEffect(()=>{if(!running)return;const id=setInterval(step,speed);return()=>clearInterval(id)},[running,speed,mode]);
 return <main><header><div><small>EXPERIMENTAL COMPUTATIONAL NEUROSCIENCE</small><h1>FLY BRAIN LAB</h1></div><div className="status"><i/> {mode==='warehouse'?'WAREHOUSE CONTROLLER · 96 NEURONS':'SYNTHETIC SNN · 96 NEURONS'}</div></header>
 <section className="toolbar"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="station">ROOM 01 · Station Control</option><option value="warehouse">ROOM 10 · Fly Warehouse</option></select><button onClick={()=>setRunning(!running)}>{running?'PAUSE':'RUN EXPERIMENT'}</button><button onClick={step}>STEP</button><button onClick={()=>init()}>RESET</button><label>speed <input type="range" min="30" max="500" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label></section>
 <div className="grid">{mode==='warehouse'?<Warehouse s={state}/>:<Station s={state}/>}<section className="panel"><h2>NEURAL ACTIVITY</h2><div className="neurons">{Array.from({length:96},(_,i)=><i key={i} className={neural.spikes?.[i]?'fire':''}/>)}</div><p className="action">BRAIN ACTION → <strong>{neural.action?.toUpperCase()}</strong></p></section><section className="panel log"><h2>EXPERIMENT RECORDER</h2>{events.map((x,i)=><code key={i}>{x}</code>)}</section><section className="panel"><h2>PROTOCOL</h2><p>{mode==='warehouse'?'Task: fulfill truck orders while respecting FIFO. Metrics include score, FIFO violations, distance and truck waiting time.':'Task: maintain station integrity under disturbances.'}</p><p className="warn">PHASE A CONTROL: synthetic controller. Real connectome modes are being integrated separately.</p></section></div></main>}
function Station({s}){return <section className="panel room"><h2>ROOM 01 — STATION CONTROL</h2><div className="machine"><div className="tank">COOLING<br/><strong>{s.cooling?'ON':'OFF'}</strong></div><div className="core">THERMAL CORE<br/><strong>{(s.temp||0).toFixed(1)}°C</strong></div><div className="tank">WATER PUMP<br/><strong>{s.pump?'ON':'OFF'}</strong></div></div><div className="meters"><Meter n="ENERGY" v={s.energy||0}/><Meter n="WATER" v={s.water||0}/><Meter n="INTEGRITY" v={s.integrity||0}/></div></section>}
function Warehouse({s}){const slots=s.slots||[],f=s.fork||{x:0,y:0};return <section className="panel room"><h2>ROOM 10 — FLY WAREHOUSE</h2><div className="wh"><div className="floor">{Array.from({length:54},(_,i)=>{const x=i%9,y=Math.floor(i/9),p=slots.find(q=>q.x===x&&q.y===y);return <div className="cell" key={i}>{p?<span className="pallet">{p.sku}<small>{p.id} · L{p.lot}</small></span>:null}{f.x===x&&f.y===y?<b className="fork">FLY▸{f.load?' '+f.load.id:''}</b>:null}{x===8&&y===5?<em>DOCK</em>:null}</div>})}</div></div><div className="whstats"><b>SCORE {s.score||0}</b><b>FIFO ERR {s.violations||0}</b><b>DIST {s.distance||0}</b><b>WAIT {s.truckWait||0}</b></div><div className="orders">{(s.orders||[]).map(o=><span key={o.id}>{o.id}: {o.sku} {o.loaded}/{o.qty} · {o.rule}</span>)}</div></section>}
function Meter({n,v}){return <div><label>{n}<b>{Math.max(0,v).toFixed(1)}%</b></label><span><i style={{width:`${Math.max(0,v)}%`}}/></span></div>}
createRoot(document.getElementById('root')).render(<App/>);
