import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SyntheticBrain} from './brain/SyntheticBrain';
import {ControlRoom} from './rooms/ControlRoom';
import {WarehouseRoom} from './rooms/WarehouseRoom';
import {WarehouseBrain} from './brain/WarehouseBrain';
import {WarehouseV2} from './rooms/WarehouseV2';
import {ReachTrainer} from './training/ReachTrainer';
import {brainInfo} from './brain/BrainRegistry';
import {runWarehouseBatch} from './experiments/BatchRunner';
import {experimentStore} from './experiments/ExperimentStore';
import './style.css';
function App(){
 const [mode,setMode]=useState('training1'),[trainingBrain,setTrainingBrain]=useState('synthetic96'),[running,setRunning]=useState(false),[speed,setSpeed]=useState(100),[neural,setNeural]=useState({spikes:[],action:'wait'}),[events,setEvents]=useState([]),[flyCount,setFlyCount]=useState(4),[brainMode,setBrainMode]=useState('synthetic96'),[batch,setBatch]=useState([]);const brain=useRef(),room=useRef();const [state,setState]=useState({});
 const init=(m=mode)=>{setRunning(false);if(m==='training1'){room.current=new ReachTrainer(trainingBrain);brain.current=null}else if(m==='warehouse2'){room.current=new WarehouseV2(2026,flyCount);brain.current=null}else if(m==='warehouse'){room.current=new WarehouseRoom(71);brain.current=new WarehouseBrain(71)}else{room.current=new ControlRoom(42);brain.current=new SyntheticBrain(42)}setState(room.current.step('wait'));setNeural({spikes:[],action:'wait'});setEvents([])};
 useEffect(()=>init(mode),[mode,trainingBrain]);
 const step=()=>{if(mode==='training1'){const s=room.current.step();setState(s);setEvents((s.history||[]).slice(-14).reverse().map(h=>`TRIAL ${h.trial} · ${h.success?'SUCCESS':'FAIL'} · ${h.steps} steps · reward ${h.reward.toFixed(2)}`));return}if(mode==='warehouse2'){const s=room.current.step();setState(s);setEvents((s.events||[]).slice(0,18));if(s.finished)setRunning(false);return}const b=brain.current.step(room.current.sensors());const s=room.current.step(b.action);setNeural(b);setState(s);setEvents(e=>[`#${s.t} ${b.action.toUpperCase()} ${mode==='warehouse'?`score ${s.score} / FIFO ${s.violations}`:`T ${s.temp.toFixed(1)}° / integrity ${s.integrity.toFixed(1)}%`}`,...e].slice(0,14));if((s.integrity!==undefined&&s.integrity<=0)||(mode==='warehouse'&&s.orders.every(o=>o.loaded>=o.qty)))setRunning(false)};
 useEffect(()=>{if(!running)return;const id=setInterval(step,speed);return()=>clearInterval(id)},[running,speed,mode]);
 return <main><header><div><small>EXPERIMENTAL COMPUTATIONAL NEUROSCIENCE</small><h1>FLY BRAIN LAB</h1></div><div className="status"><i/> {mode==='warehouse2'?'WAREHOUSE v2 · ':mode==='warehouse'?'WAREHOUSE CONTROLLER · 96 NEURONS':'SYNTHETIC SNN · 96 NEURONS'}</div></header>
 <section className="toolbar"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="training1">TRAINING 001 · Reach the pallet</option><option value="station">ROOM 01 · Station Control</option><option value="warehouse">ROOM 10 · Fly Warehouse v1</option><option value="warehouse2">ROOM 11 · Warehouse v2 · Swarm</option></select>{mode==='training1'&&<select value={trainingBrain} onChange={e=>setTrainingBrain(e.target.value)}><option value="synthetic96">Synthetic 96 · READY</option><option value="fafb">FAFB v783 Fixed · DATASET REQUIRED</option><option value="fafbPlastic">FAFB v783 Plastic · DATASET REQUIRED</option></select>}{mode==='warehouse2'&&<select value={flyCount} onChange={e=>{const n=+e.target.value;setFlyCount(n);room.current=new WarehouseV2(2026,n);setState(room.current.step())}}><option value="1">1 FLY</option><option value="2">2 FLIES</option><option value="4">4 FLIES</option><option value="8">8 FLIES</option><option value="16">16 FLIES</option><option value="32">32 FLIES</option></select>}{mode==='warehouse2'&&<select value={brainMode} onChange={e=>setBrainMode(e.target.value)}><option value="synthetic96">Synthetic 96</option><option value="synthetic1k">Synthetic 1K</option><option value="synthetic10k">Synthetic 10K</option><option value="fafb" disabled>FAFB 139K · runtime pending</option><option value="fafbPlastic" disabled>FAFB Plastic · runtime pending</option></select>}<button onClick={()=>setRunning(!running)}>{running?'PAUSE':'RUN EXPERIMENT'}</button><button onClick={step}>STEP</button><button onClick={()=>init()}>RESET</button>{mode==='warehouse2'&&<button onClick={()=>{const rs=runWarehouseBatch({count:10,flies:flyCount});rs.forEach(r=>experimentStore.record({...r,brain:brainMode}));setBatch(rs)}}>BATCH ×10</button>}<label>speed <input type="range" min="30" max="500" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label></section>
 <div className="grid">{mode==='training1'?<Training1 s={state}/>:mode==='warehouse2'?<Warehouse2 s={state} brainMode={brainMode}/>:mode==='warehouse'?<Warehouse s={state}/>:<Station s={state}/>}<section className="panel"><h2>{mode==='training1'?'BRAIN / TRAINING STATE':mode==='warehouse2'?'SWARM STATUS':'NEURAL ACTIVITY'}</h2>{mode==='training1'?<TrainingState s={state}/>:mode==='warehouse2'?<div className="flylist">{(state.flies||[]).map(f=><code key={f.id}>FLY {f.id}: {f.status} · z{f.z.toFixed(1)} · {f.target?.order||'—'}</code>)}</div>:<div className="neurons">{Array.from({length:96},(_,i)=><i key={i} className={neural.spikes?.[i]?'fire':''}/>)}</div>}{mode!=='warehouse2'&&mode!=='training1'&&<p className="action">BRAIN ACTION → <strong>{neural.action?.toUpperCase()}</strong></p>}</section><section className="panel log"><h2>EXPERIMENT RECORDER</h2>{events.map((x,i)=><code key={i}>{typeof x==='string'?x:`#${x.t} · ${x.message}`}</code>)}</section>{mode==='warehouse2'&&batch.length>0&&<section className="panel log"><h2>BATCH RESULTS</h2><code>runs {batch.length} · complete {batch.filter(r=>r.reason==='complete').length} · deadlock {batch.filter(r=>r.reason==='deadlock').length}</code><code>avg ticks {Math.round(batch.reduce((a,r)=>a+r.ticks,0)/batch.length)}</code><code>avg score {(batch.reduce((a,r)=>a+r.score,0)/batch.length).toFixed(1)}</code>{batch.slice(0,10).map((r,i)=><code key={i}>seed {r.seed} · {r.reason} · {r.completed}/{r.total} · {r.ticks} ticks</code>)}</section>}<section className="panel"><h2>PROTOCOL</h2><p>{mode==='training1'?'Experiment 001: the controller receives only normalized egocentric sensor signals (bearing, relative proximity, speed/contact). It is not given target coordinates or the correct action. Reward is based on progress toward contact. Brain state persists across trials.':mode==='warehouse2'?'Task: complete all warehouse transport orders with multiple reach trucks. Rack locations have 1–6 levels. Current phase tests routing, lifting, blocking and swarm coordination.':mode==='warehouse'?'Task: fulfill truck orders while respecting FIFO. Metrics include score, FIFO violations, distance and truck waiting time.':'Task: maintain station integrity under disturbances.'}</p><p className="warn">CONTROL BRAIN: plastic synthetic SNN. This establishes the training protocol before the same sensor/action interface is connected to the Drosophila connectome.</p></section></div></main>}
function Training1({s}){const w=s.world||{},a=w.agent||{x:12,y:82,heading:0},t=w.target||{x:76,y:18},path=w.path||[];const pts=path.map(p=>p.join(',')).join(' ');const hist=s.history||[],last20=hist.slice(-20),rate=last20.length?Math.round(last20.filter(x=>x.success).length/last20.length*100):0;return <section className="panel room"><h2>TRAINING 001 — REACH THE PALLET</h2><div className="trainarena"><svg viewBox="0 0 100 100" aria-label="Training arena"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth=".45" opacity=".35"/><rect x={t.x-3} y={t.y-3} width="6" height="6" className="targetbox"/><g transform={`translate(${a.x} ${a.y}) rotate(${a.heading*180/Math.PI})`}><path d="M 4 0 L -3 -2.5 L -3 2.5 Z" className="agentmark"/></g></svg></div><div className="whstats"><b>TRIAL {s.trial||1}</b><b>STEP {s.steps||0}/700</b><b>SUCCESS 20 {rate}%</b><b>EPSILON {((s.brain?.epsilon)||0).toFixed(3)}</b></div><div className="sensorbar"><span>FRONT {(w.sensors?.front||0).toFixed(2)}</span><span>LEFT {(w.sensors?.left||0).toFixed(2)}</span><span>RIGHT {(w.sensors?.right||0).toFixed(2)}</span><span>DIST {(w.sensors?.distance||0).toFixed(2)}</span></div></section>}
function TrainingState({s}){const h=s.history||[],success=h.filter(x=>x.success).length;return <div className="flylist"><code>BRAIN: {s.brain?.mode==='fafb'?'FAFB v783 Fixed':s.brain?.mode==='fafbPlastic'?'FAFB v783 Plastic':'Plastic Synthetic SNN (control)'}</code><code>STATUS: {s.brain?.status||'ready'}</code>{s.brain?.message&&<code>{s.brain.message}</code>}<code>Trials completed: {h.length}</code><code>Successful: {success}</code><code>Plasticity retained between trials: YES</code><code>Target coordinates exposed to brain: NO</code><code>Correct action exposed to brain: NO</code></div>}

function Station({s}){return <section className="panel room"><h2>ROOM 01 — STATION CONTROL</h2><div className="machine"><div className="tank">COOLING<br/><strong>{s.cooling?'ON':'OFF'}</strong></div><div className="core">THERMAL CORE<br/><strong>{(s.temp||0).toFixed(1)}°C</strong></div><div className="tank">WATER PUMP<br/><strong>{s.pump?'ON':'OFF'}</strong></div></div><div className="meters"><Meter n="ENERGY" v={s.energy||0}/><Meter n="WATER" v={s.water||0}/><Meter n="INTEGRITY" v={s.integrity||0}/></div></section>}
function Warehouse({s}){const slots=s.slots||[],f=s.fork||{x:0,y:0};return <section className="panel room"><h2>ROOM 10 — FLY WAREHOUSE</h2><div className="wh"><div className="floor">{Array.from({length:54},(_,i)=>{const x=i%9,y=Math.floor(i/9),p=slots.find(q=>q.x===x&&q.y===y);return <div className="cell" key={i}>{p?<span className="pallet">{p.sku}<small>{p.id} · L{p.lot}</small></span>:null}{f.x===x&&f.y===y?<b className="fork">FLY▸{f.load?' '+f.load.id:''}</b>:null}{x===8&&y===5?<em>DOCK</em>:null}</div>})}</div></div><div className="whstats"><b>SCORE {s.score||0}</b><b>FIFO ERR {s.violations||0}</b><b>DIST {s.distance||0}</b><b>WAIT {s.truckWait||0}</b><b>CATALOG {s.catalogueSize||0} SKU</b><b>INBOUND {s.inboundCount||0}</b></div><div className="orders">{(s.orders||[]).map(o=><span key={o.id}>{o.id}: {o.product}/{o.package} · {o.sku} · {o.loaded}/{o.qty} · {o.rule} · cap {o.physicalCapacity} · {(o.loadedWeight/1000).toFixed(1)}t</span>)}</div></section>}
function Warehouse2({s,brainMode}){const racks=s.racks||[],flies=s.flies||[];return <section className="panel room"><h2>ROOM 11 — WAREHOUSE v2 · MULTI-AGENT</h2><div className="v2map">{racks.map((r,i)=><div key={i} className="rackv2" style={{left:(r.x/18*100)+'%',top:(r.y/24*100)+'%'}} title={`A${r.aisle+1}-B${r.bay+1} · ${r.levels} levels`}><span>{r.levels}</span></div>)}{(s.docks||[]).map((d,i)=><div key={'d'+i} className="dockv2" style={{left:(d.x/18*100)+'%',top:(d.y/24*100)+'%'}}>D{i+1}</div>)}{flies.map(f=><div key={'f'+f.id} className="flyv2" style={{left:(f.x/18*100)+'%',top:(f.y/24*100)+'%'}}>{f.id}<small>L{f.z.toFixed(0)}</small></div>)}</div><div className="whstats"><b>FLIES {s.flyCount||0}</b><b>BRAIN {brainInfo(brainMode).name}</b><b>RACKS {racks.length}</b><b>PALLETS {(s.inventory||[]).length}</b><b>DONE {s.completed||0}</b><b>COLLISIONS {s.collisions||0}</b><b>SCORE {(s.score||0).toFixed(1)}</b></div><div className="orders">{(s.orders||[]).map(o=><span key={o.id}>{o.id} · {o.sku} · {o.done}/{o.qty} · DOCK {o.dock+1}</span>)}</div></section>}

function Meter({n,v}){return <div><label>{n}<b>{Math.max(0,v).toFixed(1)}%</b></label><span><i style={{width:`${Math.max(0,v)}%`}}/></span></div>}
createRoot(document.getElementById('root')).render(<App/>);
